# Generated by Django 5.1.7 on 2025-03-31 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0002_organismo_created_at_organismo_updated_at'),
        ('usuarios', '0002_remove_usuario_telefono_usuario_organismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organismos.organismo'),
        ),
    ]
