# Generated by Django 5.1.7 on 2025-04-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_created_at_usuario_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='organismo',
        ),
    ]
