# Generated by Django 5.1.7 on 2025-04-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0002_organismo_created_at_organismo_updated_at'),
        ('usuarios', '0006_usuario_organismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organismos.organismo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Visualizador')], default='admin', max_length=20),
        ),
    ]
