# Generated by Django 5.1.7 on 2025-04-04 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0003_tipoorganismo_alter_organismo_options_and_more'),
        ('usuarios', '0007_alter_usuario_organismo_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones_email',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones_sistema',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones en el sistema'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='organismo',
            field=models.ForeignKey(blank=True, help_text='Organismo al que pertenece el usuario (solo para usuarios de organismos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='organismos.organismo', verbose_name='Organismo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin_sma', 'Administrador SMA'), ('organismo', 'Usuario de Organismo'), ('ciudadano', 'Ciudadano')], default='ciudadano', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('dispositivo', models.CharField(blank=True, max_length=255, verbose_name='Dispositivo')),
                ('navegador', models.CharField(blank=True, max_length=255, verbose_name='Navegador')),
                ('exitoso', models.BooleanField(default=True, verbose_name='Acceso exitoso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de acceso',
                'verbose_name_plural': 'Historial de accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='light', max_length=20, verbose_name='Tema preferido')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('token_notificaciones', models.CharField(blank=True, max_length=255, verbose_name='Token de notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
