# Generated by Django 5.1.7 on 2025-04-05 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidas', '0002_componente_alter_logmedida_options_and_more'),
        ('organismos', '0003_tipoorganismo_alter_organismo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('publico', models.BooleanField(default=False, help_text='Indica si este tipo de reporte es accesible para ciudadanos', verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('parametros', models.JSONField(blank=True, null=True, verbose_name='Parámetros')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo generado')),
                ('publico', models.BooleanField(default=False, help_text='Indica si este reporte es accesible para ciudadanos', verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('componentes', models.ManyToManyField(blank=True, related_name='reportes', to='medidas.componente', verbose_name='Componentes')),
                ('organismos', models.ManyToManyField(blank=True, related_name='reportes', to='organismos.organismo', verbose_name='Organismos')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.tiporeporte', verbose_name='Tipo de Reporte')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('grafico_barras', 'Gráfico de Barras'), ('grafico_lineas', 'Gráfico de Líneas'), ('grafico_torta', 'Gráfico de Torta'), ('tabla', 'Tabla'), ('contador', 'Contador'), ('mapa', 'Mapa')], max_length=20, verbose_name='Tipo')),
                ('configuracion', models.JSONField(help_text='Configuración de la visualización en formato JSON', verbose_name='Configuración')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('componentes', models.ManyToManyField(blank=True, related_name='visualizaciones', to='medidas.componente', verbose_name='Componentes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organismos', models.ManyToManyField(blank=True, related_name='visualizaciones', to='organismos.organismo', verbose_name='Organismos')),
            ],
            options={
                'verbose_name': 'Visualización',
                'verbose_name_plural': 'Visualizaciones',
                'ordering': ['-destacado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('etiqueta', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('tipo_parametro', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('seleccion', 'Selección'), ('multiple', 'Selección Múltiple'), ('booleano', 'Sí/No')], max_length=20, verbose_name='Tipo de Parámetro')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('valor_defecto', models.CharField(blank=True, max_length=255, verbose_name='Valor por defecto')),
                ('opciones', models.JSONField(blank=True, help_text='Opciones para tipos de selección, en formato JSON', null=True, verbose_name='Opciones')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='reportes.tiporeporte', verbose_name='Tipo de Reporte')),
            ],
            options={
                'verbose_name': 'Parámetro de Reporte',
                'verbose_name_plural': 'Parámetros de Reportes',
                'ordering': ['tipo_reporte', 'orden'],
                'unique_together': {('tipo_reporte', 'nombre')},
            },
        ),
    ]
