# Generated by Django 5.1.7 on 2025-03-31 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organismo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
