# Generated by Django 5.1.7 on 2025-04-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismos', '0002_organismo_created_at_organismo_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Organismo',
                'verbose_name_plural': 'Tipos de Organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='organismo',
            options={'ordering': ['nombre'], 'verbose_name': 'Organismo', 'verbose_name_plural': 'Organismos'},
        ),
        migrations.RemoveField(
            model_name='organismo',
            name='sigla',
        ),
        migrations.AddField(
            model_name='organismo',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='ContactoOrganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='organismos.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'Contacto de Organismo',
                'verbose_name_plural': 'Contactos de Organismos',
                'ordering': ['organismo', '-es_principal', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='organismo',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organismos', to='organismos.tipoorganismo', verbose_name='Tipo de organismo'),
            preserve_default=False,
        ),
    ]
