# Generated by Django 5.1.7 on 2025-04-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0001_initial'),
        ('organismos', '0003_tipoorganismo_alter_organismo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('color', models.CharField(blank=True, help_text='Código hexadecimal del color, ej: #FF5733', max_length=7, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='logmedida',
            options={'ordering': ['-fecha'], 'verbose_name': 'Log de Medida', 'verbose_name_plural': 'Logs de Medidas'},
        ),
        migrations.AlterModelOptions(
            name='medida',
            options={'ordering': ['codigo'], 'verbose_name': 'Medida', 'verbose_name_plural': 'Medidas'},
        ),
        migrations.RemoveField(
            model_name='medida',
            name='usuario',
        ),
        migrations.AddField(
            model_name='logmedida',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='codigo',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('retrasada', 'Retrasada'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='medida',
            name='fecha_inicio',
            field=models.DateField(default='2025-04-04', verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='fecha_termino',
            field=models.DateField(default='2025-04-04', verbose_name='Fecha de término'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='porcentaje_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de avance'),
        ),
        migrations.AddField(
            model_name='medida',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='logmedida',
            name='accion',
            field=models.CharField(max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='logmedida',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='logmedida',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medidas.medida', verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='logmedida',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_medidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='AsignacionMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_coordinador', models.BooleanField(default=False, help_text='Indica si el organismo es el coordinador principal de esta medida', verbose_name='Es coordinador')),
                ('descripcion_responsabilidad', models.TextField(blank=True, verbose_name='Descripción de responsabilidad')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='medidas.medida', verbose_name='Medida')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_medidas', to='organismos.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'Asignación de Medida',
                'verbose_name_plural': 'Asignaciones de Medidas',
                'unique_together': {('medida', 'organismo')},
            },
        ),
        migrations.AddField(
            model_name='medida',
            name='responsables',
            field=models.ManyToManyField(related_name='medidas_asignadas', through='medidas.AsignacionMedida', to='organismos.organismo', verbose_name='Organismos responsables'),
        ),
        migrations.AddField(
            model_name='medida',
            name='componente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='medidas.componente', verbose_name='Componente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RegistroAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de avance')),
                ('descripcion', models.TextField(verbose_name='Descripción del avance')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Archivo de evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='medidas.medida', verbose_name='Medida')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='organismos.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'Registro de Avance',
                'verbose_name_plural': 'Registros de Avance',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
